version: '3.8'

services:
  gateway:
    build:
      context: .
      dockerfile: Dockerfile
    image: portkey-gateway:latest
    container_name: portkey-gateway
    ports:
      - "8787:8787"
    environment:
      # Langfuse Configuration
      - LANGFUSE_PUBLIC_KEY=${LANGFUSE_PUBLIC_KEY}
      - LANGFUSE_SECRET_KEY=${LANGFUSE_SECRET_KEY}
      - LANGFUSE_BASE_URL=${LANGFUSE_BASE_URL:-https://cloud.langfuse.com}

      # Optional: Add other environment variables
      - NODE_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8787/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    # Optional: Resource limits
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
        reservations:
          cpus: '1'
          memory: 512M
